services:
    _defaults:
        autowire: true
        public: false

    Lle\PdfGeneratorBundle\Action\ShowRessourceAction:
        arguments: ['@Lle\PdfGeneratorBundle\Generator\PdfGenerator']
        tags: [controller.service_arguments]