services:
    _defaults:
        autowire: true
        public: false

    Lle\PdfGeneratorBundle\Action\ShowRessourceAction:
        arguments: ['@doctrine.orm.entity_manager','@Lle\PdfGeneratorBundle\Generator\PdfGenerator']
        tags: [controller.service_arguments]