services:
    _defaults:
        autowire: true
        public: false

    Lle\PdfGeneratorBundle\Action\ShowRessourceAction:
        arguments: ['@Lle\PdfGeneratorBundle\Generator\PdfGenerator']
        tags: [controller.service_arguments]

    Lle\PdfGeneratorBundle\Action\ShowPdfAction:
        arguments: ['@Lle\PdfGeneratorBundle\Generator\PdfGenerator']
        tags: [controller.service_arguments]

    Lle\PdfGeneratorBundle\Action\CheckPdfAction:
        arguments: ['@Lle\PdfGeneratorBundle\Generator\PdfGenerator', '@doctrine.orm.default_entity_manager', '@session.flash_bag']
        tags: [controller.service_arguments]