lle.pdf_generator:
        public: false
        class:  'Lle\PdfGeneratorBundle\Generator\WordToPdfGenerator'
        arguments: []

Lle\PdfGeneratorBundle\Generator\WordToPdfGenerator: '@lle.pdf_generator'