services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    Lle\PdfGeneratorBundle\Generator\WordToPdfGenerator:
        class:  'Lle\PdfGeneratorBundle\Generator\WordToPdfGenerator'
        arguments: ['@twig', '@lle.pdf.reorganizer_twig_parser', '@lle.pdf.obj_accessor']

    lle.pdf.reorganizer_twig_parser:
        class:  'Lle\PdfGeneratorBundle\Parsing\ReorganizerTwigParser'
        arguments: []

    lle.pdf.obj_accessor:
        class:  'Lle\PdfGeneratorBundle\ObjAccess\Accessor'
        arguments: []

    Lle\PdfGeneratorBundle\Parsing\ReorganizerTwigParser: "@lle.pdf.reorganizer_twig_parser"

    Lle\PdfGeneratorBundle\ObjAccess\Accessor: "@lle.pdf.obj_accessor"