services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    Lle\PdfGeneratorBundle\Generator\WordToPdfGenerator:
        class:  'Lle\PdfGeneratorBundle\Generator\WordToPdfGenerator'
        arguments: ['@twig', '@lle.pdf.obj_accessor']
        tags: ['lle.pdf.generator']

    Lle\PdfGeneratorBundle\Generator\PdfGenerator:
        arguments: ["@doctrine.orm.default_entity_manager",  '@kernel','@parameter_bag', !tagged lle.pdf.generator]

    lle.pdf.obj_accessor:
        class:  'Lle\PdfGeneratorBundle\ObjAccess\Accessor'
        arguments: []

    Lle\PdfGeneratorBundle\ObjAccess\Accessor: "@lle.pdf.obj_accessor"