lle_pdf_generator_show_ressource:
    path:      /pdf/{id}/show/ressource
    defaults:
        _controller: Lle\PdfGeneratorBundle\Action\ShowRessourceAction

lle_pdf_generator_show_pdf:
    path:      /pdf/{id}/show/pdf
    defaults:
        _controller: Lle\PdfGeneratorBundle\Action\ShowPdfAction

lle_pdf_generator_check_pdf:
    path:      /pdf/{id}/check/pdf
    defaults:
        _controller: Lle\PdfGeneratorBundle\Action\CheckPdfAction

lle_pdf_generator_admin_balise:
    path: /admin/balise
    defaults:
        _controller: Lle\PdfGeneratorBundle\Controller\BaliseController::index

lle_pdf_generator_admin_model_balise:
    path: /admin/{module}
    defaults:
        _controller: Lle\PdfGeneratorBundle\Controller\BaliseController::getBalises
